
title: <p align="center"> Sajan Kedia </p>

description:
  <p align="center">
   
  <br>   
  A data enthusiast who loves to deep dive into the processes and gather meaningful insights from the business numbers and design strategies to optimize them.
  <br>
  </p>
theme: jekyll-theme-minimal
